### PR TITLE
hapsycloud: task 1 to 9 done

### PR DESCRIPTION
**Pull request by hapsycloud**
This is the final draft of task 1 to 9 being created in the pull. The earlier ones were a fail for some reason and I just have closed the pull request for those earlier ones.

### CODE REVIEW

**Comment by saba-ja** [comment]
As I mentioned in the class you should submit your pull request to **YOUR OWN** repo. You are submitting the pull request to my repository which is the upstream repo that you forked from.

**Comment by saba-ja** [comment]
Basically your pull request should be 
from `hapsycloud:devel` to `hapsycloud:master`

Currently you are submitting it as 
`hapsycloud:devel` to `saba-ja:master`

**Comment by hapsycloud** [comment]
Thank you Saba and Sorry I was a bit behind.

**Comment by saba-ja** [comment]
No worries! We learn better when we struggle. By end of this semester you will be fluent with Git workflow.

**Comment by hapsycloud** [comment]
Sorry, I have a question actually, since that was Task 13, and I saw
automatic merge, so I thought I should keep going in the task. I ended up
reaching task 19 before I was able to correctly "Merge pull request" the
devel to master. Would that be bad? If so, should I close everything again
and start from scratch?

**Comment by saba-ja** [comment]
No there won't be any problem. You can merge to the master branch at any time if you do not have any merge conflicts.
It looks like you already have pushed your changes to master branch without creating a pull request from your devel.
Basically you directly pushed the changes to the master branch, therefore both your branches have the same content and there won't be anything to merge.
You can see it from this link:
https://github.com/hapsycloud/git-workshop/compare/master...hapsycloud:devel

**Comment by hapsycloud** [comment]
Awesome! so that means i can continue in task 20 correct?
That would be deleting the devel branch in the github.
[image: image.png]
So deleting Both the "Your branch" and "Active Branch" correct?

**Comment by saba-ja** [comment]
Just delete the devel branch as shown below:

Screen Shot 2021-08-31 at 3 19 28 PM

**Comment by hapsycloud** [comment]
Thank you for that information Saba.
Now I have encountered a new problem which is at Task 25, when I have to
type in "$ git push origin content_update". I get rejected as shown below
in the picture.
[image: image.png]
is there any way I can fix that? I see that it says fetch first but I'm
unsure if that is the right way to go. I tried alternative hints as well
such as "$ git pull" but that turned into a mess which made me do some
messy work just to get back on track again.

Thank you for your time and consideration.

**Comment by saba-ja** [comment]
First, I can't see the image. It seems it is just `[image: image.png]`

Second: This the merge request issue we created purposely so you can see the Merge conflict.
You should not see this if you are on "content_update" branch, but if you are on master branch and you are trying to push your changes to the master branch you will get this merge conflict issue.

To resolve this from your local 'git checkout content_update' then push to the remote 'git push origin content_update'

**Comment by hapsycloud** [comment]
Well from Task 22 - 25 was tasked to run with "git checkout
content_update". I got  a conflict before merging pull request
This down below is what was given to me in Git Bash after I did:
$ git branch content_update
$ git checkout content_update
$ git add .
$ git commit -m 'your-github-id: updated README file'
$ git push origin content_update

```Result````
kevin /C/Users/kevin/Documents/git-workshop (content_update)
$ git push origin content_update
To https://github.com/hapsycloud/git-workshop.git
 ! [rejected]        content_update -> content_update (fetch first)
error: failed to push some refs to '
https://github.com/hapsycloud/git-workshop.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Or was this suppose to happen?

**Comment by saba-ja** [comment]
That is the merge conflict error. 
You are getting this because you changed the README file on GitHub webpage while you were in content_update branch.
If you go to this URL you can see your change history on content_update branch:
https://github.com/hapsycloud/git-workshop/commits/content_update

The first one is README update where you updated the README file directly from GitHub page while you were on content_update branch.

So in this case this merge conflict is expected.

**Comment by saba-ja** [comment]
You should be able to resolve this by the followings:

```
$ git fetch -a
$ git branch -a
```
You should see list of all branches from both local and remote. If you see remotes/origin/content_update in the list then run:

```
$ git checkout content_update
$ git merge origin/content_update
```
And you should get a message saying you have a merge conflict.
Then open the README file in vscode and remove the parts that you do not need.

Then git add and git commit and git push.

**Comment by hapsycloud** [comment]
Thank you very much for your help in the workshop tasks, I have realized
every time I put the keyword **bold** I also do a new branch which messes
up everything. So I did it one by one in order which eventually led to
correcting everything. I have finally finished the task. I also have
finished lab assignment 0. I made a lot of mistakes in the commit for Lab
assignment 0 but I was able to get the final output. I'll keep in mind next
time that the commit needs to change every time. Sorry about that. Should I
redo the assignment due to the commit being constant?

**Comment by saba-ja** [comment]
Good job on finishing the lab. There is no need to redo the assignment if the final result is correct. Commits show your trend of work and your progress. Mistakes are fine as long as they are not in the final submission.

**Pull request closed without merging**
